// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0oQh7TBp50QSP5j1xA3PeZWdFkjMSVrU',
    appId: '1:245819340727:web:944a1d5da655a4f64f5a32',
    messagingSenderId: '245819340727',
    projectId: 'gamenest-e6263',
    authDomain: 'gamenest-e6263.firebaseapp.com',
    storageBucket: 'gamenest-e6263.firebasestorage.app',
    measurementId: 'G-EMJTK40MT8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5mjQebEyMmnPQYjrhbYSrUDCd8Ifimn0',
    appId: '1:245819340727:ios:80c2bc7914b49a2b4f5a32',
    messagingSenderId: '245819340727',
    projectId: 'gamenest-e6263',
    storageBucket: 'gamenest-e6263.firebasestorage.app',
    iosBundleId: 'com.fofo.games',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRqh2p2Pb5hZwUHr2JB5Pb8rViJWB4sjo',
    appId: '1:245819340727:android:99800e5bdd02f4074f5a32',
    messagingSenderId: '245819340727',
    projectId: 'gamenest-e6263',
    storageBucket: 'gamenest-e6263.firebasestorage.app',
  );

}